# Generated by Django 5.1.5 on 2025-02-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_remove_item_condition_alter_item_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
